const datas = [
    {
        "style": "Arrocha",
        "songs" : [
            {
                "cantor": "Tierry",
                "thumb": "./src/thumbs/arrocha/tierry-acertounamosca.webp",
                "play" : "Play",
                "musicas" : [
                    "Cracudo",
                    "Acertou Na Mosca",
                    "Tifany",
                    "Hb20",
                    "Hakearam-me",
                    "Choque Térmico",
                    "Profissional Do Amor",
                    "Prego E Martelo",
                    "Coração De Espelho",
                    "Disco Arranhado",
                    "Atestado",
                    "Tudo Ok",
                    "Chega Doi",
                    "O Que É O Que É",
                    "Chifre Em Pó",
                ],
            },
            {
                "cantor": "Pablo e Assas Livres",
                "thumb": "./src/thumbs/arrocha/asas-livres-pablo-e-asas-livres-retro.webp",
                "play" : "Play",
                "musicas" : [
                    "Tudo Azul",
                    "Cristina",
                    "Vou Te Procurar",
                    "Todas As Coisas Do Mundo",
                    "Perigo",
                    "Perdoa",
                    "Dona De Mim",
                    "Voa Livre",
                    "Nosso Juramento",
                    "Nordestina",
                    "Amigo Seu",
                    "Solidão",
                    "Quero Ser Feliz",
                    "Passou Da Conta",
                    "Nem Mais Uma Dúvida",
                    "Raiva De Você",
                    "Faz Amor Comigo",
                    "Por Deus Eu Te Amo",
                    "Arrocha",
                    "Deusa De Itamaracá",
                    "Ela É A Outra",
                    "A Ferro E Fogo",
                    "Tô Por Aí",
                    "Ta Com Raiva De Mim",
                    "Tchau Tchau Amor"
                ],
            },
            {
                "cantor": "Tierry",
                "thumb": "./src/thumbs/arrocha/tierry-role-de-milhoes.webp",
                "play" : "Play",
                "musicas" : [
                    "Porque Bebi",
                    "Pai É Quem Cria",
                    "Diabinha",
                    "Ainda Tô Pagando",
                    "Me Apaixonei Me Apeguei",
                    "Revoei"
                ],
            },
        ]
    },
    {
        "style": "Forró",
        "songs" : [
            {
                "cantor": "Wesley Safadão",
                "thumb": "./src/thumbs/forro/wesley-safadao.webp",
                "play" : "Play",
                "musicas" : [
                    "Me Supera Em Off - WS",
                    "Depende - WS",
                    "Malvada - WS",
                    "Soca Tudo - WS",
                    "Mal Feito - WS",
                    "Pandora - WS",
                    "Eu Já Tava Bem - WS",
                    "Formosa - WS",
                    "Viciada Em Paredão - WS",
                    "Malvadão - WS",
                    "Saudade No Talo - WS",
                    "Tu Vai Rodar - WS",
                    "Voz Do Paredão - WS",
                    "Com Choro Ou Sem Choro - WS",
                    "Menina Debochada - WS",
                    "No Chão Novinha - WS",
                    "Por Enquanto - Menina Veneno - Medley - WS"
                ],
            },
            {
                "cantor": "Rafinha Big Love",
                "thumb": "./src/thumbs/forro/rafinha-big-love.webp",
                "play" : "Play",
                "musicas" : [
                    "Meu Amor É Seu - RBL",
                    "Proteção De Tela - RBL",
                    "Aquelas Coisas - RBL",
                    "Superação Digital - RBL",
                    "Cena De Amor - RBL",
                    "Outra Vida - RBL",
                    "Você Beberia Ou Não Beberia - RBL",
                    "Diferente Das Diferentes - RBL",
                    "Chega E Senta - RBL",
                    "Se For Amor - RBL",
                    "Termina Comigo - RBL",
                    "Horizonte Azul - RBL",
                    "Larga Dessa Bad - RBL",
                    "Tô Com Saudade - RBL",
                    "O Processo É Natural - RBL",
                    "Eu Tô Aí - RBL",
                    "Dona De Mim - RBL",
                    "Rolê - RBL",
                    "Imaturidade - RBL",
                    "Máquina Zero - RBL",
                    "Não Acaba Nã - RBLo"
                ],
            },
            {
                "cantor": "Calcinha Preta",
                "thumb": "./src/thumbs/forro/calcinha-preta-belem.webp",
                "play" : "Play",
                "musicas" : [
                    "Abelha Que Virou Anjo - CP",
                    "A Calcinha É Nossa - CP",
                    "Cobertor - CP",
                    "Manchete Nos Jornais - CP",
                    "Louca Por Ti - CP",
                    "E O Vento Levou - CP",
                    "Um Degrau Na Escada - CP",
                    "Faço Chover - CP",
                    "Mágica - CP",
                    "Te Acho Tão Linda - CP",
                    "Seu Namorado - CP",
                    "Hoje A Noite - CP",
                    "Armadilha - CP",
                    "Babydoll - CP",
                    "Por Amor O Que É Que Eu Vou Fazer - CP",
                    "Ja Me Acostumei - CP",
                    "Não Me Deixe Agora - CP",
                    "Ainda Te Amo - CP",
                    "O Navio E O Mar - CP",
                    "Liga Pra Mim - CP",
                    "Novo Namorado - CP",
                    "Fica Comigo - CP",
                    "Furunfa Te Quero Namorar - CP"
                ],
            }
            
        ]
    },
    {
        "style": "Hip Hop / Rap",
        "songs" : [
            {
                "cantor": "Hungria Hip Hop",
                "thumb": "./src/thumbs/hip hop_rap/hungria-hip-hop.jpg",
                "play" : "Play",
                "musicas" : [
                    "Beijo Com Trap",
                    "Coração De Aço",
                    "Lembranças",
                    "Primeiro Milhão",
                    "Um Pedido",
                    "Carruagem",
                    "Detalhes",
                    "Astronauta",
                    "Garota E Diamante",
                    "Dubai",
                    "Não Tenho Freio",
                    "De Aro 20",
                    "Fumaça",
                    "O Playboy Rodou",
                    "Apaga A Luz",
                    "Cama De Casal",
                    "Insônia"
                ],
            },
            {
                "cantor": "Poesia Acústica",
                "thumb": "./src/thumbs/hip hop_rap/poesia-acustica.jpg",
                "play" : "Play",
                "musicas" : [
                    "1 - Descompasso Do Compasso",
                    "2 - Sobre Nós",
                    "3 - Capricorniana",
                    "4 - Todo Mundo Odéia Acústico",
                    "5 - Teu Popô",
                    "6 - Era Uma Vez",
                    "7 - Céu Azul",
                    "8 - Amor E Samba",
                    "9 - Melhor Forma",
                    "10 - Recomeçar",
                    "11 - Nada Mudou",
                    "12 - Pra Sempre"
                ],
            },
            {
                "cantor": "Tribo Da Periferia",
                "thumb": "./src/thumbs/hip hop_rap/tribo-da-periferia.webp",
                "play" : "Play",
                "musicas" : [
                    "Cegonha",
                    "Tema",
                    "Dia De Poderoso",
                    "Gelo E Gin",
                    "Rolê Sagrado",
                    "Segunda Noite",
                    "Festival De Nós Dois",
                    "O Retorno E Lei",
                    "Fechamento De Sempre",
                    "Resiliência"
                ],
            },
        ]
    },
    {
        "style": "Pagode",
        "songs" : [
            {
                "cantor": "Péricles",
                "thumb": "./src/thumbs/pagode/pericles-acustico.webp",
                "play" : "Play",
                "musicas" : [
                    "Linguagem Dos Olhos",
                    "Se Eu Largar O Freio",
                    "Jogo De Sedução",
                    "Eu E Você Sempre",
                    "Melhor Eu Ir"
                ],
            },
            {
                "cantor": "Pixote",
                "thumb": "./src/thumbs/pagode/pixote-chiclete.jpg",
                "play" : "Play",
                "musicas" : [
                    "Ele E Ela",
                    "Adeus",
                    "Belisca",
                    "Chiclete",
                    "Você Ta No Celular",
                    "Só A Lua"
                ],
            },
            
        ]
    },
    {
        "style": "Piseiro",
        "songs" : [
            {
                "cantor": "João Gomes",
                "thumb": "./src/thumbs/piseiro/joao-gomes-digo-ou-nao-digo.webp",
                "play" : "Play",
                "musicas" : [
                    "Digo Ou Não Digo - JG",
                    "Dengo - JG",
                    "Terra Prometida - JG",
                    "Meu Cafofo - JG",
                    "Não Aceito Mais - JG",
                    "Lembra - JG",
                    "Sem Você - JG",
                    "Amando Você - JG",
                    "Pode Ficar - JG",
                    "Se Essa Vida Fosse Um Filme - JG",
                    "De Janeiro A Janeiro - JG",
                    "Quebrou a Cara - JG",
                    "Me Adora - JG",
                    "Só Voce e Eu - JG",
                    "Dentro De Mim - JG",
                    "Te Amar é Bom Demais - JG",
                ],
            },
            {
                "cantor": "Mari Fernandez",
                "thumb": "./src/thumbs/piseiro/mari-fernandez-tente-nao-beber.webp",
                "play" : "Play",
                "musicas" : [
                    "Parada Louca - MF",
                    "Quem Vale Menos - MF",
                    "Teu Amigo Cuidou - MF",
                    "A Maior Saudade - MF",
                    "Olha O Que O Amor Me Faz - MF",
                    "Vida Que Segue - MF",
                    "Você Beberia Ou Não Beberia - MF",
                    "Esqueça-me Se For Capaz - MF",
                    "De Vez Em Sempre - MF",
                    "Ainda Tem Sentimento - MF",
                    "Bebi Até Cair - MF",
                    "Alvejante - MF",
                    "Saudade Carinhosa - MF",
                    "É Pra Lascar O Coração - MF",
                    "Marionete - MF",
                    "Story Mentiroso - MF"
                ],
            },
            {
                "cantor": "Zé Vaqueiro",
                "thumb": "./src/thumbs/piseiro/ze-vaqueiro-o-original.webp",
                "play" : "Play",
                "musicas" : [
                    "Eu Tenho Medo - ZV",
                    "Cangote - ZV", 
                    "Letícia - ZV",
                    "Forró No Interior - ZV",
                    "Meu Mel - ZV",
                    "Decida - ZV",
                    "Confidencial - ZV",
                    "Foi Amor - ZV",
                    "Na Boca Do Litrão - ZV",
                    "Graveto - ZV",
                    "Só Basta Você Me Ligar - ZV",
                    "Nem Por Um Milhão - ZV",
                    "Matuto De Verdade - ZV",
                    "Roxinho - ZV",
                    "Passarinho - ZV"
                ],
            },
            {
                "cantor": "Barões Da Pisadinha",
                "thumb": "./src/thumbs/piseiro/os-baroes-da-pisadinha-2020.webp",
                "play" : "Play",
                "musicas" : [
                    "Batom De Ouro",
                    "Galera Do Interior",
                    "Dançar Forró Beijando",
                    "Chupadinha",
                    "Desce Do Cavalo",
                    "Já Que Me Ensinou A Beber",
                    "Mamãe Que É Mamãe",
                    "Quem Me Colocou Pra Beber",
                    "O Piseiro Xtourou",
                    "Status",
                    "Com Ele É Cinema Comigo É Cama",
                    "Investe Em Mim",
                    "O Matuto Se Apaixonou",
                    "O Povo Gosta É Do Piseiro",
                    "Bumbum No Paredão",
                    "Vem Me Amar",
                    "Paredão Loló",
                    "Era Eu",
                    "Meu Forró",
                    "Bebezinha",
                    "Eu O Meu Cavalo E Ela",
                    "Monta Logo Vai",
                    "Mente Milionária",
                    "Ta Rocheda"
                ],
            }
            ,
            {
                "cantor": "Tarcísio Do Acordeon",
                "thumb": "./src/thumbs/piseiro/tarcisio-do-acordeon.webp",
                "play" : "Play",
                "musicas" : [
                    "Eu Tô Aí",
                    "Me Esqueca Se Puder",
                    "Amor Reserva",
                    "Eu Gosto É De Problema",
                    "Imaturidade",
                    "Proteção De Tela",
                    "Coleção De Otário",
                    "Meu Sonho",
                    "A Dor Mais Doida",
                    "Eu Tenho A Senha",
                    "Tem Que Ser Agora",
                    "Hoje Doi",
                    "Vaqueiro Ferido"
                ],
            }
        ]
    },
    {
        "style": "Pop",
        "songs" : [
            {
                "cantor": "Olívia Rodrigo",
                "thumb": "./src/thumbs/pop/olivia_rodrigo.jpg",
                "play" : "Play",
                "musicas" : [
                    "Brutal",
                    "Traitor",
                    "Drivers License",
                    "Step Forward 3 Steps Back",
                    "Deja Vu",
                    "Good 4 U",
                    "Enough For You",
                    "Happier",
                    "Jealousy Jealousy",
                    "Favorite Crime",
                    "Hompe Ur Ok",
                ],
            },            
        ]
    },
    {
        "style": "Romântico",
        "songs" : [
            {
                "cantor": "Nivaldo Marques",
                "thumb": "./src/thumbs/romantico/nivaldo-marques-pra-bailar.webp",
                "play" : "Play",
                "musicas" : [
                    "Tomar Uma Na Zona",
                    "Acorda Pedrinho",
                    "Morena Com o Corpo Bronzeado",
                    "Ela É Problemática",
                    "Tem Cabaré Essa Noite",
                    "Malhado E Gostoso",
                    "Não Pega Ninguém Ainda",
                    "Revoada",
                    "Ui Ai",
                    "Balanço Da Rede",
                    "Capa Do Celular",
                    "Desce Com O Dedo Na Boca",
                    "Malandrinha",
                    "Fim De Semana",
                    "Louca Magia",
                    "O Que Será De Nós",
                    "Devolva Meu Coração"
                ],
            },
            
        ]
    },
    {
        "style": "Sertanejo",
        "songs" : [
            {
                "cantor": "Gusttavo Lima",
                "thumb": "./src/thumbs/sertanejo/butecoInBoston.jpg",
                "play" : "Play",
                "musicas" : [
                    "O Ex da Sua Vida",
                    "Nota de Repúdio",
                    "Bloqueado",
                    "Quebrando Protocolo",
                    "Não Me Arranha",
                    "Inventor dos Amores",
                    "Eu Tava Lá",
                    "I Love You Baby",
                    "Lado Emocional",
                    "Ficha Limpa",
                    "Declaração de Amor",
                    "Em Qualquer Lugar",
                    "Se",
                    "Larga essa Rua",
                    "Pendência",
                    "Prefiro Nem Saber",
                    "Teste de Farmácia",
                    "Tempo de Beber",
                    "Te Amo Cada Vez Mais"
                ],
            },
            {
                "cantor": "Henrique e Juliano",
                "thumb": "./src/thumbs/sertanejo/henrique-juliano-menos-e-mais.jpg",
                "play" : "Play",
                "musicas" : [
                    "Três Corações",
                    "Se Joga Na Minha Vida",
                    "Metade Da Estrada",
                    "Quem pegou Pegou",
                    "Palmas Pro Amor",
                    "Quando Você Vem",
                    "Sala De Espera",
                    "Menos É Mais",
                    "Rua Recaída",
                    "Lembrança Boa",
                    "Completa Aí",
                    "Beijadamente Calculado",
                    "Arruma Um Cantinho",
                    "Desbeijar Minha Boca",
                    "Fim Ou Intervalo",
                    "Vai Que Bebereis",
                    "Granada",
                    "Cidade Vizinha",
                    "Garrafas Vazias",
                    "Eu E A Saudade"
                ],
            },
            {
                "cantor": "Mayara e Maraisa",
                "thumb": "./src/thumbs/sertanejo/maiaraeMaraisa.jpg",
                "play" : "Play",
                "musicas" : [
                    "10%",
                    "A pergunta part. Henrique e Juliano",
                    "Ai que vontade",
                    "Aí Eu bebo",
                    "Bebo litro part. Jorge e Mateus",
                    "Coração Infectado",
                    "GPS",
                    "Sorte Que Cê Beija Bem",
                    "A Culpa é Dele feat. Maiara e Maraisa",
                    "Melhor Terminar",
                    "Minha Pessoa Errada",
                    "Motel part. Marília Mendonça",
                    "Nem Tchum",
                    "No Dia Do Seu Casamento",
                    "Não abro mão",
                    "Oi Sumido",
                    "Quase Tudo",
                    "Se Olha No Espelho part. Cristiano Araújo",
                    "Traí sim part Zé Neto e Cristiano",
                    "Separada"
                ],
            },
            {
                "cantor": "Zé neto e Cristiano",
                "thumb": "./src/thumbs/sertanejo/zenetoeCristiano.jpg",
                "play" : "Play",
                "musicas" : [
                    "Vamo Tomar Uma",
                    "Você Beberia Ou Não Beberia",
                    "Waze Falou",
                    "Amigo Taxista",
                    "Batendo o Dente",
                    "Bebi Minha Bicicleta",
                    "Beijou Meia Cidade",
                    "Botequinho",
                    "Chaaama",
                    "Ela E Ela",
                    "Estelionato Afetivo",
                    "Fica Pra Dormir",
                    "Marcha De Núpcias",
                    "Melhor Ser Uma Saldade",
                    "Minha Vontade De Te Amar",
                    "Notificação Preferida",
                    "Pegador",
                    "Pior Dos Piores",
                    "Vida Noturna",
                    "Você Não Merece"
                ],
            }
        ]
    },
    {
        "style": "Vaquejada",
        "songs" : [
            {
                "cantor": "Amado Edilson",
                "thumb": "./src/thumbs/vaquejada/amado-edilson.jpeg",
                "play" : "Play",
                "musicas" : [
                    "Couro De Boi - AE",
                    "A Mulher Da Blusa Amarela - AE",
                    "Minha Mulher É Aquela - AE",
                    "Último Adeus De Um Vaqueiro - AE",
                    "A Mulher Que Mais Amei - AE",
                    "Nunca Mais Vi Minha Amada - AE",
                    "Resposta Da Blusa Amarela - AE",
                    "A Culpa Foi Toda Dela - AE",
                    "Serenata Da Montanha - AE",
                    "Jovem Abandonado - AE",
                    "Mulher Completa - AE",
                    "Dono Dela Sou Eu - AE",
                    "Gosto Detudo Que Ela Faz - AE",
                    "Mulher Do Cachaceiro - AE",
                    "Coqueiro Da Bahia - AE",
                    "Resposta Mulher Casada - AE",
                    "Paixão Não Mata Ninguém - AE",
                    "Cajueiro - AE",
                    "A Distância - AE",
                    "Mulher Bandid - AEa"
                ],
            }
        ]
    }
]