const datas = [
    {
        "style": "Arrocha",
        "songs" : [
            {
                "cantor": "Pablo e Assas Livres",
                "thumb": "thumbs/arrocha/asas-livres-pablo-e-asas-livres-retro.webp",
                "play" : "Play",
                "musicas" : [
                    "Tudo Azul",
                    "Cristina",
                    "Vou Te Procurar",
                    "Todas As Coisas Do Mundo",
                    "Perigo",
                    "Perdoa",
                    "Dona De Mim",
                    "Voa Livre",
                    "Nosso Juramento",
                    "Nordestina",
                    "Amigo Seu",
                    "Solidão",
                    "Quero Ser Feliz",
                    "Passou Da Conta",
                    "Nem Mais Uma Dúvida",
                    "Raiva De Você",
                    "Faz Amor Comigo",
                    "Por Deus Eu Te Amo",
                    "Arrocha",
                    "Deusa De Itamaracá",
                    "Ela É A Outra",
                    "A Ferro E Fogo",
                    "Tô Por Aí",
                    "Ta Com Raiva De Mim",
                    "Tchau Tchau Amor"
                ],
            },
            {
                "cantor": "Tierry",
                "thumb": "thumbs/arrocha/tierry-role-de-milhoes.webp",
                "play" : "Play",
                "musicas" : [
                    "Porque Bebi",
                    "Pai É Quem Cria",
                    "Diabinha",
                    "Ainda Tô Pagando",
                    "Me Apaixonei Me Apeguei",
                    "Revoei"
                ],
            },
            
        ]
    },
    {
        "style": "Forró",
        "songs" : [
            {
                "cantor": "Calcinha Preta",
                "thumb": "thumbs/forro/calcinha-preta-belem.webp",
                "play" : "Play",
                "musicas" : [
                    "Abelha Que Virou Anjo",
                    "A Calcinha É Nossa",
                    "Cobertor",
                    "Manchete Nos Jornais",
                    "Louca Por Ti",
                    "E O Vento Levou",
                    "Um Degrau Na Escada",
                    "Faço Chover",
                    "Mágica",
                    "Te Acho Tão Linda",
                    "Seu Namorado",
                    "Hoje A Noite",
                    "Armadilha",
                    "Babydoll",
                    "Por Amor O Que É Que Eu Vou Fazer",
                    "Ja Me Acostumei",
                    "Não Me Deixe Agora",
                    "Ainda Te Amo",
                    "O Navio E O Mar",
                    "Liga Pra Mim",
                    "Novo Namorado",
                    "Fica Comigo",
                    "Furunfa Te Quero Namorar"
                ],
            },
        ]
    },
    {
        "style": "Hip Hop / Rap",
        "songs" : [
            {
                "cantor": "Hungria Hip Hop",
                "thumb": "thumbs/hip hop_rap/hungria-hip-hop.jpg",
                "play" : "Play",
                "musicas" : [
                    "Beijo Com Trap",
                    "Coração De Aço",
                    "Lembranças",
                    "Primeiro Milhão",
                    "Um Pedido",
                    "Carruagem",
                    "Detalhes",
                    "Astronauta",
                    "Garota E Diamante",
                    "Dubai",
                    "Não Tenho Freio",
                    "De Aro 20",
                    "Fumaça",
                    "O Playboy Rodou",
                    "Apaga A Luz",
                    "Cama De Casal",
                    "Insônia"
                ],
            },
        ]
    },
    {
        "style": "Pagode",
        "songs" : [
            {
                "cantor": "Péricles",
                "thumb": "thumbs/pagode/pericles-acustico.webp",
                "play" : "Play",
                "musicas" : [
                    "Linguagem Dos Olhos",
                    "Se Eu Largar O Freio",
                    "Jogo De Sedução",
                    "Eu E Você Sempre",
                    "Melhor Eu Ir"
                ],
            },
            {
                "cantor": "Pixote",
                "thumb": "thumbs/pagode/pixote-chiclete.jpg",
                "play" : "Play",
                "musicas" : [
                    "Ele E Ela",
                    "Adeus",
                    "Belisca",
                    "Chiclete",
                    "Você Ta No Celular",
                    "Só A Lua"
                ],
            },
            
        ]
    },
    {
        "style": "Romântico",
        "songs" : [
            {
                "cantor": "Nivaldo Marques",
                "thumb": "thumbs/romantico/nivaldo-marques-pra-bailar.webp",
                "play" : "Play",
                "musicas" : [
                    "Tomar Uma Na Zona",
                    "Acorda Pedrinho",
                    "Morena Com o Corpo Bronzeado",
                    "Ela É Problemática",
                    "Tem Cabaré Essa Noite",
                    "Malhado E Gostoso",
                    "Não Pega Ninguém Ainda",
                    "Revoada",
                    "Ui Ai",
                    "Balanço Da Rede",
                    "Capa Do Celular",
                    "Desce Com O Dedo Na Boca",
                    "Malandrinha",
                    "Fim De Semana",
                    "Louca Magia",
                    "O Que Será De Nós",
                    "Devolva Meu Coração"
                ],
            },
            
        ]
    },
    {
        "style": "Sertanejo",
        "songs" : [
            {
                "cantor": "Gusttavo Lima",
                "thumb": "thumbs/sertanejo/butecoInBoston.jpg",
                "play" : "Play",
                "musicas" : [
                    "O Ex da Sua Vida",
                    "Nota de Repúdio",
                    "Bloqueado",
                    "Quebrando Protocolo",
                    "Não Me Arranha",
                    "Inventor dos Amores",
                    "Eu Tava Lá",
                    "I Love You Baby",
                    "Lado Emocional",
                    "Ficha Limpa",
                    "Declaração de Amor",
                    "Em Qualquer Lugar",
                    "Se",
                    "Larga essa Rua",
                    "Pendência",
                    "Prefiro Nem Saber",
                    "Teste de Farmácia",
                    "Tempo de Beber",
                    "Te Amo Cada Vez Mais"
                ],
            },
            {
                "cantor": "Mayara e Maraisa",
                "thumb": "thumbs/sertanejo/maiaraeMaraisa.jpg",
                "play" : "Play",
                "musicas" : [
                    "10 (Ao Vivo em Goiânia)",
                    "A pergunta part. Henrique e Juliano - DVD Reflexo",
                    "Ai que vontade - DVD Reflexo",
                    "Aí Eu bebo - EP Aqui Em Casa",
                    "Bebo litro part. Jorge e Mateus - DVD Reflexo",
                    "Coração Infectado",
                    "GPS",
                    "Sorte Que Cê Beija Bem - DVD Ao Vivo Em Campo Grande",
                    "A Culpa é Dele feat. Maiara e Maraisa (Agora é Que São Elas 2)",
                    "Melhor Terminar - DVD Ao Vivo Em Campo Grande",
                    "Minha Pessoa Errada - EP Aqui Em Casa",
                    "Motel part. Marília Mendonça (Ao Vivo em Goiânia)",
                    "Nem Tchum - DVD Reflexo",
                    "No Dia Do Seu Casamento (Ao Vivo em Goiânia)",
                    "Não abro mão - DVD Reflexo",
                    "Oi Sumido - EP Aqui Em Casa",
                    "Quase Tudo - Agora é que são elas 2",
                    "Se Olha No Espelho (part. Cristiano Araújo) [Ao Vivo em Goiânia]",
                    "Traí sim part. Zé Neto e Cristiano - DVD Reflexo",
                    "Separada - DVD Reflexo"
                ],
            },
            {
                "cantor": "João Gomes",
                "thumb": "thumbs/sertanejo/joao-gomes-digo-ou-nao-digo.webp",
                "play" : "Play",
                "musicas" : [
                    "Digo Ou Não Digo",
                    "Dengo",
                    "Terra Prometida",
                    "Meu Cafofo",
                    "Não Aceito Mais",
                    "Lembra",
                    "Sem Você",
                    "Amando Você",
                    "Pode Ficar",
                    "Se Essa Vida Fosse Um Filme",
                    "De Janeiro A Janeiro",
                    "Quebrou a Cara",
                    "Me Adora",
                    "Só Voce e Eu",
                    "Dentro De Mim",
                    "Te Amar é Bom Demais",
                ],
            },
            {
                "cantor": "Zé neto e Cristiano",
                "thumb": "thumbs/sertanejo/zenetoeCristiano.jpg",
                "play" : "Play",
                "musicas" : [
                    "VAMO TOMAR UMA - DVD Chaaama",
                    "VOCÊ BEBERIA OU NÃO BEBERIA - DVD Chaaama",
                    "WAZE FALOU - EP TARJA PRETA",
                    "Amigo Taxista - DVD Um Novo Sonho",
                    "BATENDO O DENTE - EP TARJA PRETA",
                    "BEBI MINHA BICICLETA - DVD Por Mais Beijos Ao Vivo",
                    "BEIJOU MEIA CIDADE - DVD Chaaama",
                    "BOTEQUINHO - DVD Chaaama",
                    "CHAAAMA - DVD Chaaama",
                    "ELA E ELA - DVD Chaaama",
                    "Estelionato Afetivo - Douglas e Vinícius - Part. Zé Neto e Cristiano",
                    "FICA PRA DOMIR - DVD Chaaama",
                    "MARCHA DE NÚPCIAS - DVD Chaaama",
                    "MELHOR SER UMA SAUDADE - EP TARJA PRETA",
                    "MINHA VONTADE DE TE AMAR - DVD Chaaama",
                    "NOTIFICAÇÃO PREFERIDA - EsqueceOMundoLaFora",
                    "Pegador part. João Bosco e Vinícius",
                    "PIOR DOS PIORES - EP TARJA PRETA",
                    "VIDA NOTURNA - DVD Chaaama",
                    "VOCÊ NÃO MERECE - EP TARJA PRETA"
                ],
            },
            {
                "cantor": "Zé neto e Cristiano",
                "thumb": "thumbs/sertanejo/zenetoeCristiano.jpg",
                "play" : "Play",
                "musicas" : [
                    "VAMO TOMAR UMA - DVD Chaaama",
                    "VOCÊ BEBERIA OU NÃO BEBERIA - DVD Chaaama",
                    "WAZE FALOU - EP TARJA PRETA",
                    "Amigo Taxista - DVD Um Novo Sonho",
                    "BATENDO O DENTE - EP TARJA PRETA",
                    "BEBI MINHA BICICLETA - DVD Por Mais Beijos Ao Vivo",
                    "BEIJOU MEIA CIDADE - DVD Chaaama",
                    "BOTEQUINHO - DVD Chaaama",
                    "CHAAAMA - DVD Chaaama",
                    "ELA E ELA - DVD Chaaama",
                    "Estelionato Afetivo - Douglas e Vinícius - Part. Zé Neto e Cristiano",
                    "FICA PRA DOMIR - DVD Chaaama",
                    "MARCHA DE NÚPCIAS - DVD Chaaama",
                    "MELHOR SER UMA SAUDADE - EP TARJA PRETA",
                    "MINHA VONTADE DE TE AMAR - DVD Chaaama",
                    "NOTIFICAÇÃO PREFERIDA - EsqueceOMundoLaFora",
                    "Pegador part. João Bosco e Vinícius",
                    "PIOR DOS PIORES - EP TARJA PRETA",
                    "VIDA NOTURNA - DVD Chaaama",
                    "VOCÊ NÃO MERECE - EP TARJA PRETA"
                ],
            },
            {
                "cantor": "Zé neto e Cristiano",
                "thumb": "thumbs/sertanejo/zenetoeCristiano.jpg",
                "play" : "Play",
                "musicas" : [
                    "VAMO TOMAR UMA - DVD Chaaama",
                    "VOCÊ BEBERIA OU NÃO BEBERIA - DVD Chaaama",
                    "WAZE FALOU - EP TARJA PRETA",
                    "Amigo Taxista - DVD Um Novo Sonho",
                    "BATENDO O DENTE - EP TARJA PRETA",
                    "BEBI MINHA BICICLETA - DVD Por Mais Beijos Ao Vivo",
                    "BEIJOU MEIA CIDADE - DVD Chaaama",
                    "BOTEQUINHO - DVD Chaaama",
                    "CHAAAMA - DVD Chaaama",
                    "ELA E ELA - DVD Chaaama",
                    "Estelionato Afetivo - Douglas e Vinícius - Part. Zé Neto e Cristiano",
                    "FICA PRA DOMIR - DVD Chaaama",
                    "MARCHA DE NÚPCIAS - DVD Chaaama",
                    "MELHOR SER UMA SAUDADE - EP TARJA PRETA",
                    "MINHA VONTADE DE TE AMAR - DVD Chaaama",
                    "NOTIFICAÇÃO PREFERIDA - EsqueceOMundoLaFora",
                    "Pegador part. João Bosco e Vinícius",
                    "PIOR DOS PIORES - EP TARJA PRETA",
                    "VIDA NOTURNA - DVD Chaaama",
                    "VOCÊ NÃO MERECE - EP TARJA PRETA"
                ],
            },
            {
                "cantor": "Zé neto e Cristiano",
                "thumb": "thumbs/sertanejo/zenetoeCristiano.jpg",
                "play" : "Play",
                "musicas" : [
                    "VAMO TOMAR UMA - DVD Chaaama",
                    "VOCÊ BEBERIA OU NÃO BEBERIA - DVD Chaaama",
                    "WAZE FALOU - EP TARJA PRETA",
                    "Amigo Taxista - DVD Um Novo Sonho",
                    "BATENDO O DENTE - EP TARJA PRETA",
                    "BEBI MINHA BICICLETA - DVD Por Mais Beijos Ao Vivo",
                    "BEIJOU MEIA CIDADE - DVD Chaaama",
                    "BOTEQUINHO - DVD Chaaama",
                    "CHAAAMA - DVD Chaaama",
                    "ELA E ELA - DVD Chaaama",
                    "Estelionato Afetivo - Douglas e Vinícius - Part. Zé Neto e Cristiano",
                    "FICA PRA DOMIR - DVD Chaaama",
                    "MARCHA DE NÚPCIAS - DVD Chaaama",
                    "MELHOR SER UMA SAUDADE - EP TARJA PRETA",
                    "MINHA VONTADE DE TE AMAR - DVD Chaaama",
                    "NOTIFICAÇÃO PREFERIDA - EsqueceOMundoLaFora",
                    "Pegador part. João Bosco e Vinícius",
                    "PIOR DOS PIORES - EP TARJA PRETA",
                    "VIDA NOTURNA - DVD Chaaama",
                    "VOCÊ NÃO MERECE - EP TARJA PRETA"
                ],
            }
        ]
    },
    
]